baseURL = 'https://surviverse.netlify.app/'
languageCode = 'fr-fr'
title = 'Surviverse Wiki'

# Change the default theme to be use when building the site with Hugo
theme = "learn"

# For search functionality
[outputs]
	home = [ "HTML", "RSS", "JSON"]
	
[params]
	customCSS = ["css/custom.css"]
	editURL = "https://github.com/jabossu/surviversewiki-hugo/edit/main/content/"
	author = "Topaway"
	description = "Wiki Officiel des Star Survivors"

[[menu.shortcuts]]
    name = "<i class='fas fa-map-marked-alt'></i> Worldmap"
    url = "/worldmap/unmined.index.html"
    weight = 20

[[menu.shortcuts]]
    name='<i class="fas fa-question-circle"></i> FAQ'
    url = "/FAQ"
    weight = 30

[[menu.shortcuts]]
    name='<br><center><img alt="GitHub last commit (branch)" src="https://img.shields.io/github/last-commit/jabossu/surviversewiki-hugo/main"></center>'
    url = "https://github.com/jabossu/surviversewiki-hugo"
    weight = 3000
